new Vue({
  el:'#app',
  data(){
    return{
      menus:[
        {
          label:'TOP',
          path:'./ex_index.html'
        },
        {
          label:'PROGRAM',
          path:'./ex_program.html'
        },
        {
          label:'DATE',
          path:'./ex_date.html'
        }
      ],
      song:[
        {
          music:'カノン'
        },
        {
          music:'四季'
        },
        {
          music:'月光'
        }
      ],
      obj:[
        {
          date:'date:11月3日'
        },
        {
          date:'time:15:00-16:00'
        },
        {
          date:'place:市民ホール'
        }
      ]
    };
  }
}
)